### ISSUE TITLE
Add a way to modify reviews (and/or delete them)

### ISSUE THREAD

**Issue by orselane** [TrustyUnitReview/ProductReview#72]
A bit related to #70 :

We have no way to delete or modify a review currently. 

- We could possibly add a button in the own user profile to do so. 
- Or, we could link to the product in the profile, with the ability to modify your review directly on the product page. We could re-use the normal review box with a simple confirmation to modify the review. Maybe add a delete review button as well in the same location?

**Comment by Mayukh-G** [comment]
The Form will change to patch reviews instead of posting a new one.

Deleting is going to be ignored for now.
